/**
 * Smoke tests — generated by the playwright-smoke skill.
 *
 * LOCAL-ONLY: These tests assume the bridge SQLite at
 * ~/whatsapp-mcp/whatsapp-bridge/store/messages.db exists. CI is intentionally
 * skipped — the viewer depends on Carl's Mac-local WhatsApp data.
 *
 * Run with: `npm test`
 */
import { test, expect, type ConsoleMessage, type Page } from "@playwright/test";

const STATIC_ROUTES = [
  "/",
  "/drops",
  "/sql",
  "/stats",
  "/needs-reply",
  "/contacts",
  "/insights",
  "/insights/reply-latency",
  "/insights/initiator",
  "/insights/calendar",
  "/insights/drifting",
  "/insights/words",
  "/insights/reactions",
  "/insights/awkward",
  "/insights/simulator",
  "/insights/snapshot",
  "/insights/topics",
  "/insights/birthdays",
  "/iluxury",
];

// A real group jid from the local bridge. WhatsApp has two group-jid formats:
//   <creator-phone>-<unix-ts>@g.us   (legacy, exposes the creator's phone)
//   12036<long-random>@g.us          (post-2022, opaque)
// Use the new format here — no PII embedded.
const SAMPLE_GROUP_JID = "120363072670308311@g.us";

const DYNAMIC_ROUTES = [
  { path: `/chat/${encodeURIComponent(SAMPLE_GROUP_JID)}`, description: "chat detail (group)" },
  { path: `/chat/${encodeURIComponent(SAMPLE_GROUP_JID)}/replay`, description: "chat replay (group)" },
  { path: "/drops?days=1", description: "drops dashboard 1-day window" },
  { path: "/drops?days=30", description: "drops dashboard 30-day window" },
  { path: "/stats?days=7", description: "stats dashboard 7-day window" },
  { path: "/insights/awkward?silence=72", description: "awkward 72h silence window" },
  { path: "/insights/topics?days=14", description: "topics 14-day window" },
];

type ApiRoute = {
  path: string;
  method: "GET" | "POST";
  body?: unknown;
  okStatus?: number[];
};

const API_ROUTES: ApiRoute[] = [
  // Valid read-only query — must return 200
  { path: "/api/sql", method: "POST", body: { query: "SELECT 1 AS x" }, okStatus: [200] },
  // Write attempt — must be rejected with 400 (read-only enforcement)
  { path: "/api/sql", method: "POST", body: { query: "DELETE FROM messages" }, okStatus: [400] },
  // Summarize without chat_jid — tests the route is alive without spending Anthropic tokens
  { path: "/api/summarize", method: "POST", body: {}, okStatus: [400] },
  // iLuxury claim toggle without required fields — tests route alive + validation
  { path: "/api/iluxury/claim", method: "POST", body: {}, okStatus: [400] },
  // Simulator validation — both chat_jid + draft are required
  { path: "/api/simulate", method: "POST", body: {}, okStatus: [400] },
  // Compose re-opener validation — chat_jid required
  { path: "/api/compose-reopener", method: "POST", body: {}, okStatus: [400] },
  // Snapshot OG image — chat query param required
  { path: "/api/snapshot", method: "GET", okStatus: [400] },
  // Snapshot with a valid chat — should return 200 PNG
  { path: `/api/snapshot?chat=${encodeURIComponent(SAMPLE_GROUP_JID)}`, method: "GET", okStatus: [200] },
  // NOTE: /api/topics intentionally NOT tested — first call per 24h spends Anthropic tokens.
  // Birthdays ICS — always 200, returns text/calendar
  { path: "/api/birthdays.ics", method: "GET", okStatus: [200] },
];

function listenForBadConsole(page: Page): { messages: ConsoleMessage[]; pageErrors: Error[] } {
  const messages: ConsoleMessage[] = [];
  const pageErrors: Error[] = [];
  page.on("console", (msg) => {
    if (msg.type() === "error") messages.push(msg);
  });
  page.on("pageerror", (err) => pageErrors.push(err));
  return { messages, pageErrors };
}

test.describe("smoke: static routes", () => {
  for (const route of STATIC_ROUTES) {
    test(`GET ${route} returns 200 with no console errors`, async ({ page }) => {
      const watch = listenForBadConsole(page);
      const response = await page.goto(route, { waitUntil: "domcontentloaded" });
      expect(response, `${route} produced no response`).toBeTruthy();
      expect(response!.status(), `${route} did not return 200`).toBeLessThan(400);
      await page.waitForLoadState("networkidle", { timeout: 5_000 }).catch(() => {});
      expect(
        watch.pageErrors,
        `${route} threw on page: ${watch.pageErrors.map((e) => e.message).join(" | ")}`
      ).toHaveLength(0);
      expect(
        watch.messages.map((m) => m.text()),
        `${route} logged console errors`
      ).toEqual([]);
    });
  }
});

test.describe("smoke: dynamic routes", () => {
  for (const route of DYNAMIC_ROUTES) {
    test(`GET ${route.path} (${route.description}) returns 200`, async ({ page }) => {
      const watch = listenForBadConsole(page);
      const response = await page.goto(route.path, { waitUntil: "domcontentloaded" });
      expect(response!.status(), `${route.path} did not return 200`).toBeLessThan(400);
      await page.waitForLoadState("networkidle", { timeout: 5_000 }).catch(() => {});
      expect(watch.pageErrors).toHaveLength(0);
    });
  }
});

test.describe("smoke: API route handlers", () => {
  for (const route of API_ROUTES) {
    const label = `${route.method} ${route.path}${route.body ? ` body=${JSON.stringify(route.body).slice(0, 40)}` : ""}`;
    test(`${label} → ${route.okStatus?.join(" or ") ?? "<500"}`, async ({ request }) => {
      const response =
        route.method === "GET"
          ? await request.get(route.path)
          : await request.post(route.path, { data: route.body ?? {} });
      const status = response.status();
      if (route.okStatus) {
        expect(route.okStatus, `${label} returned ${status}`).toContain(status);
      } else {
        expect(status, `${label} returned ${status}`).toBeLessThan(500);
      }
    });
  }
});

test("sidebar renders chat names from the DB", async ({ page }) => {
  await page.goto("/");
  await page.waitForLoadState("networkidle", { timeout: 5_000 }).catch(() => {});
  // Search input must be present
  await expect(page.getByPlaceholder("Search chats…")).toBeVisible();
  // Drops/Stats/SQL nav links must be present
  await expect(page.getByRole("link", { name: "Drops" })).toBeVisible();
  await expect(page.getByRole("link", { name: "Stats" })).toBeVisible();
  await expect(page.getByRole("link", { name: "SQL" })).toBeVisible();
});

test("no broken images on the homepage", async ({ page }) => {
  await page.goto("/");
  await page.waitForLoadState("networkidle", { timeout: 5_000 }).catch(() => {});
  const broken = await page.$$eval("img", (imgs) =>
    imgs
      .filter((i) => (i as HTMLImageElement).complete && (i as HTMLImageElement).naturalWidth === 0)
      .map((i) => (i as HTMLImageElement).src)
  );
  expect(broken, `Broken <img> sources: ${broken.join(", ")}`).toHaveLength(0);
});
